### ISSUE TITLE
Add pre-commit for ruff and other style checks

### ISSUE THREAD

**Issue by gcanasherrera** [cloe-org/cloelike#17]
## 📝 Issue Summary  
Integrate [Ruff](https://docs.astral.sh/ruff/) as a linter in the Continuous Integration (CI) pipeline to ensure code quality, style consistency, and early error detection across the codebase—similarly to how it's done in `euclidlilb`.  
Additionally, configure [`pre-commit`](https://pre-commit.com/) to run Ruff locally before each commit, enforcing style and linting at the source.

### 🎯 Goals / Acceptance Criteria  
- [ ] **Goal 1**: Add `ruff` as a development dependency in the project (e.g., via `pyproject.toml` or `requirements-dev.txt`).  
- [ ] **Goal 2**: Configure GitHub Actions (or the CI tool in use) to run `ruff` checks on each push and pull request.  
- [ ] **Goal 3**: Set up [`pre-commit`](https://pre-commit.com/) with a Ruff hook to automatically lint and optionally fix issues before each commit.

### 🔄 Steps to Reproduce (if applicable)  
1. Install `ruff` locally: `pip install ruff`.  
2. Add a configuration block (e.g., in `pyproject.toml` or `.ruff.toml`).  
3. Set up a GitHub Actions workflow that runs `ruff .` on CI.  
4. Install `pre-commit`: `pip install pre-commit`.  
5. Create a `.pre-commit-config.yaml` in the repo root:
   ```yaml
   repos:
     - repo: https://github.com/astral-sh/ruff-pre-commit
       rev: v0.11.12
       hooks:
         - id: ruff-check
           args: [--fix]
         - id: ruff-format
   ```
6. Run `pre-commit install` to activate hooks.  
7. Run `pre-commit run --all-files` to test the setup.  
8. Push changes and verify CI runs and fails on Ruff violations.

### ✅ Expected Outcome  
- Ruff runs automatically on every pull request or push, flagging linting issues.  
- CI fails if Ruff detects any problems, encouraging fixes before merging.  
- Developers get immediate feedback via `pre-commit` when committing locally.

### 🐞 Current Behavior (if applicable)  
Linting is not currently enforced in CI or during development. Style violations or common mistakes may slip through code reviews or be handled inconsistently across contributors.

### 📌 Additional Notes  
- Ruff is significantly faster than other Python linters (e.g., `flake8`, `pylint`).  
- Local `pre-commit` usage improves development workflow and reduces CI noise.  
- Reference config:
  ```toml
  [tool.ruff]
  select = ["E", "F", "I"]
  ignore = []
  line-length = 100
  ```

- Example GitHub Actions CI workflow:
  ```yaml
  name: Lint

  on: [push, pull_request]

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install Ruff
          run: pip install ruff
        - name: Run Ruff
          run: ruff .
  ```

### 👥 Assignees  
- @gcanasherrera
