### ISSUE TITLE
Customize the issue template chooser

### ISSUE THREAD

**Issue by gcanasherrera** [cloe-org/cloelike#20]
## 📝 Issue Summary  
The repository currently lacks a `.github/config.yaml` file to configure and customize the issue template chooser. Implementing this will allow us to present contributors with clear options (e.g., Bug Report, Feature Request, etc.) when they open a new issue, improving the quality and consistency of contributions. 

Reason: community is confused about what template to use. Let's follow [this](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).

### 🎯 Goals / Acceptance Criteria  
- [ ] **Goal 1**: Create a `.github/config.yaml` file to define issue template categories, descriptions, and default labels.  
- [ ] **Goal 2**: Ensure the template chooser displays a clean UI with all issue types.  
- [ ] **Goal 3**: Test that each issue template appears correctly when creating a new issue via GitHub's web interface.
- [ ] **Goal 4**: Make sure that all template descriptions are ingested as cloelike (no trace to cloelib whatsoever).

### 🔄 Steps to Reproduce  
1. Go to the "New Issue" page of the repository.  
2. Notice there's no structured template chooser or pre-filled guidance.  
3. Contributors may submit incomplete or miscategorized issues.

### ✅ Expected Outcome  
- GitHub presents a menu of well-defined issue templates (e.g., Bug, Feature, Enhancement).  
- Each template includes a clear description and suggested labels.  
- The `config.yaml` enforces good practices and helps first-time contributors file high-quality issues.

### 🐞 Current Behavior  
- The issue submission process is unstructured or uses only a default template.  
- Contributors might skip crucial information, leading to more back-and-forth or confusion.

### 📌 Additional Notes  
Example structure of `.github/config.yaml`:
```yaml
blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/your-org/your-repo/discussions
    about: Ask general questions or get help in the Discussions section
issue_template:
  - name: Bug Report
    description: File a bug report
    labels: [bug]
  - name: Feature Request
    description: Suggest an improvement or new feature
    labels: [enhancement]
  - name: Code Refactor
    description: Propose a cleanup or structural improvement to the code
    labels: [refactor]
```
